### ISSUE TITLE
Use composer.json instead of vendor/

### ISSUE THREAD

**Issue by stephanvierkant** [jeroendesloovere/geolocation-bundle#1]
You've added many components to the vendor directory. I think you should composer.json to have the right dependencies and put the actual app (geolocation-bundle/vendor/jeroendesloovere/geolocation-php-api) in the root of your repository.

**Comment by jeroendesloovere** [comment]
@stephanvierkant Thanks for pointing out. This is in fact true, I forgot to add a .gitignore file. Fixed it

**Comment by stephanvierkant** [comment]
You just removed your application by adding it to the .gitignore file. You have to put in the root.

**Comment by jeroendesloovere** [comment]
I removed the `/vendor` folder since, `composer install` regenerates this with all latest classes.
I want to keep my `geolocation-php-api` in a separate repo. Since many users use that class, even when they don't use Symfony Bundles...

**Comment by stephanvierkant** [comment]
My bad, you're right :)
